In [2]:
import numpy as np

In [32]:
pl1 = [1,2,3,5,-5]    #Python List 1
np.array(pl1)   # Converting it into Numpy Array

array([ 1,  2,  3,  5, -5])

In [33]:
numpy_arr = np.array(pl1)
print (numpy_arr)

[ 1  2  3  5 -5]


In [22]:
numpy_arr.shape

(5,)

In [23]:
len(numpy_arr.shape)

1

Now, going to lists into list

In [29]:
pl2 = [[1,2],[3,4]]
np.array(pl2)

array([[1, 2],
       [3, 4]])

In [30]:
np.array(pl2).shape

(2, 2)

#(2,2) means there are 2 lists inside the list and there are 2 numbers inside the inner lists.

In [27]:
len(np.array(pl2).shape)

2

Another Example

In [40]:
pl3 = [[1, 0,5], [2,4,6]]
np.array(pl3)

array([[1, 0, 5],
       [2, 4, 6]])

In [34]:
np.array(pl3).shape

(2, 3)

#(2,3) means there are 2 lists inside the list and there are 3 numbers inside the inner lists.

Common ways to create lists

In [35]:
# 1] range()
range(5)

range(0, 5)

In [36]:
list(range(5))

[0, 1, 2, 3, 4]

In [37]:
# 2] np.arange()
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
# 3] np.zeros()
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [42]:
# 4] np.ones()
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [43]:
# 5] np.random  # It is the sum module we always use.
np.random

<module 'numpy.random' from '/home/codespace/.local/lib/python3.10/site-packages/numpy/random/__init__.py'>

In [3]:
np.random.randint

<function RandomState.randint>

In [4]:
np.random.randint(5)  #Any random integer from (0,5). Output keeps on chaning randomly.

4

In [5]:
np.random.randint(5 , size=(2,3))  # To get the 2D version(Matrix)

array([[0, 3, 2],
       [4, 0, 0]])